services:
  itc.dataservice:
    image: itc.dataservice
    restart: unless-stopped
    build:
      context: .
      dockerfile: ITC.DataService/Dockerfile
    ports:
      - "5015:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      KafkaConfiguration:BootstrapServers: kafka:29092
      DataObserverConfiguration:CsvDirPath: '/mnt'
      DataObserverConfiguration:Interval: 30
    volumes:
      - C:\Users\vados\Downloads\Telegram Desktop\Data_Set_mains:/mnt
  
  itc.reportservice:
    image: itc.reportservice
    restart: unless-stopped
    build:
      context: .
      dockerfile: ITC.ReportService/Dockerfile
    ports:
      - "5016:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
  
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper
    restart: unless-stopped
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    container_name: kafka
    restart: unless-stopped
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_MESSAGE_MAX_BYTES: 1000000000 # 1GB
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  frontend:
    build: .
    ports:
      - "80:80"
