services:
  itc.dataservice:
    image: vados62625/itc-dataservice:latest
    restart: unless-stopped
    ports:
      - "5015:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      KafkaConfiguration:BootstrapServers: kafka:29092
      DataObserverConfiguration:CsvDirPath: '/mnt'
      DataObserverConfiguration:Interval: 30
    volumes:
      - /home/ITC.DataService/sourceFiles:/mnt
  
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper
    restart: unless-stopped
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    container_name: kafka
    restart: unless-stopped
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://your-public-ip:9093
      KAFKA_LISTENERS: INTERNAL://:29092,EXTERNAL://:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_MESSAGE_MAX_BYTES: 1000000000 # 1GB
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1