@ITC.DataService_HostAddress = http://localhost:5041

### Отправить CSV файл
POST {{ITC.DataService_HostAddress}}/Csv/Upload
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="example.csv"
Content-Type: text/csv

< ./example.csv
--WebAppBoundary--

###
